network:
  listen: 127.0.0.1:8181
  host: localhost
  mongodb_url: mongodb+srv://
recaptcha:
  enable: false
  secret_key:
  site_key:
security:
  master_key:
  encryption_key:
  encryption_nonce:
content:
  detect_abuse: true
  expire_hrs: 24

